[package]
name = "vortex-driver-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
tigerbeetle.path = "../../../clients/rust"
futures = { version = "0.3.31", default-features = false, features = ["executor"] }
anyhow = "1.0.93"
