name: Linux

on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  lint:
    if: inputs.version == ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./scripts/install_zig.sh
      - run: zig/zig build lint
    env:
      SOURCE_REPO: ${{ github.event.pull_request.head.repo.clone_url }}

  docs_link_spellcheck:
    if: inputs.version == ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./.github/ci/docs_check.sh

  test_on_alpine:
    if: inputs.version == ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./.github/ci/tests_on_alpine.sh

  test_on_ubuntu:
    if: inputs.version == ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          COV=1 ./.github/ci/tests_on_ubuntu.sh && \
          (cp kcov-output/test.*/cobertura.xml cov-pr.xml) || true
      - name: Upload cov-pr.xml
        uses: actions/upload-artifact@v3
        continue-on-error: true
        with:
          name: cov-pr.xml
          path: cov-pr.xml

  # Used to generate coverage information for the target of this PR.
  # Disabled while `zig build test`'s setExecCmd isn't working.
  # test_on_ubuntu_main:
  #   if: inputs.version == ''
  #   runs-on: ubuntu-latest
  #   continue-on-error: true
  #   steps:
  #     # Check out the PR, copy the tests_on_ubuntu.sh from there, checkout main.
  #     - uses: actions/checkout@v3
  #     - run: cp ./.github/ci/tests_on_ubuntu.sh /tmp/tests_on_ubuntu.sh
  #     - run: cp ./build.zig /tmp/build.zig
  #     - uses: actions/checkout@v3
  #       with:
  #         ref: 'main'

  #     - name: Fetch main commit
  #       run: echo "main-sha=$(git rev-parse HEAD)" > $GITHUB_OUTPUT
  #       id: main-sha

  #     - name: Cache cov-main.xml for main commit
  #       id: cache-cov
  #       uses: actions/cache@v3
  #       with:
  #         path: cov-main.xml
  #         key: cov-xml-${{ steps.main-sha.outputs.main-sha }}

  #     - name: Generate cov-main.xml for main commit
  #       if: steps.cache-cov.outputs.cache-hit != 'true'
  #       run: |
  #         cp /tmp/build.zig . && \
  #         COV=1 /tmp/tests_on_ubuntu.sh && \
  #         cp kcov-output/test.*/cobertura.xml cov-main.xml

  #     - name: Upload cov-main.xml
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: cov-main.xml
  #         path: cov-main.xml

  # Disabled while `zig build test`'s setExecCmd isn't working.
  # coverage:
  #   if: inputs.version == ''
  #   runs-on: ubuntu-latest
  #   needs: [test_on_ubuntu, test_on_ubuntu_main]
  #   continue-on-error: true
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/checkout@v3
  #       with:
  #         ref: 'main'
  #         path: 'tigerbeetle-main'

  #     - name: Download cov-main.xml
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: cov-main.xml
  #         path: cov-main.xml

  #     - name: Download cov-pr.xml
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: cov-pr.xml
  #         path: cov-pr.xml

  #     # The sed command below is an inline patch which fixes pycobertura for our XML files. It's
  #     # really weird that it's required at all.
  #     # The || true is because pycobertura will exit with a non-zero exit code if it finds a diff
  #     - run: |
  #         pip install pycobertura==3.2.1 && \
  #         sed -i "296s/for file_index in range(number_of_files)/for file_index in range(len(file_stats_dict['Filename']))/" ~/.local/lib/python3.10/site-packages/pycobertura/reporters.py && \

  #         pycobertura show -f html -s ./src cov-pr.xml/cov-pr.xml -o coverage.html && \
  #         (pycobertura diff -f html -o coverage-diff.html cov-main.xml/cov-main.xml cov-pr.xml/cov-pr.xml --source1 ${GITHUB_WORKSPACE}/tigerbeetle-main/src --source2 ./src || true) && \
  #         echo "# Diff To Main" > ${GITHUB_STEP_SUMMARY} && \
  #         (pycobertura diff --no-color -f markdown cov-main.xml/cov-main.xml cov-pr.xml/cov-pr.xml --source1 ${GITHUB_WORKSPACE}/tigerbeetle-main/src --source2 ./src || true) >> ${GITHUB_STEP_SUMMARY} && \
  #         echo "# PR Coverage" >> ${GITHUB_STEP_SUMMARY} && \
  #         pycobertura show -f markdown -s ./src cov-pr.xml/cov-pr.xml >> ${GITHUB_STEP_SUMMARY} && \
  #         (pycobertura diff -f github-annotation --annotation-title=kcov --annotation-message="Not covered by unit test." cov-main.xml/cov-main.xml cov-pr.xml/cov-pr.xml --source1 ${GITHUB_WORKSPACE}/tigerbeetle-main/src --source2 ./src || true) | sed 's|^::notice file=|::notice file=src/|'

  #     - name: Upload Test Coverage
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: coverage.html
  #         path: coverage.html

  #     - name: Upload Test Coverage Diff
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: coverage-diff.html
  #         path: coverage-diff.html

  benchmark:
    if: inputs.version == ''
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - run: ./scripts/benchmark.sh --transfer-count=4000

  aof:
    if: inputs.version == ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./scripts/install_zig.sh
      - run: ./.github/ci/test_aof.sh

  c_sample:
    if: inputs.version == ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./scripts/install_zig.sh
      - run: zig/zig build c_sample -Doptimize=ReleaseSafe

  # I don't like this - having everything manually listed out here, but need to think of a better
  # way to parallelize it.
  fuzz:
    if: inputs.version == ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./scripts/install_zig.sh
      - run: zig/zig build fuzz_ewah -- --seed 123
      - run: zig/zig build fuzz_lsm_segmented_array -- --seed 123
      - run: zig/zig build fuzz_lsm_tree -- --seed 123 --events-max 400
      - run: zig/zig build fuzz_lsm_manifest -- --seed 123 --events-max 400
      - run: zig/zig build fuzz_vsr_journal_format -- --seed 123
      - run: zig/zig build fuzz_vsr_superblock -- --seed 123 --events-max 3
      - run: zig/zig build fuzz_vsr_superblock_quorums -- --seed 123

      # Disabled for now, since they're slow.
      # # This both checks that the hash_log builds and acts as a regression test for
      # # https://github.com/tigerbeetle/tigerbeetle/issues/404
      # - run: zig/zig build fuzz_lsm_manifest_log -- --seed 123 --events-max 400
      # - run: zig/zig build fuzz_vsr_superblock_free_set -- --seed 123
      # - run: zig/zig build fuzz_lsm_forest -Dhash-log-mode=create -Doptimize=ReleaseSafe -- --seed 16319736705930193193 --events-max 10000 && zig/zig build fuzz_lsm_forest -Dhash-log-mode=check -- --seed 16319736705930193193 --events-max 10000

  # Check some build steps that would otherwise not get checked.
  # Things like "go_client", "java_client", "dotnet_client" are excluded here
  # because they get run in their own CI
  verify:
    if: inputs.version == ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: ./scripts/install_zig.sh
      - run: zig/zig build build_benchmark_ewah
      - run: zig/zig build build_benchmark_binary_search
      - run: zig/zig build build_benchmark_segmented_array
      - run: zig/zig build -Dtracer-backend=tracy

  # This is just a canary to make sure that the simulator compiles
  # It would be a good idea to also _run_ a single iteration,
  # but that currently has some false failures :-)
  # TODO: Make so we have a single zig build simulator that does both
  simulate:
    if: inputs.version == ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./scripts/install_zig.sh
      - run: zig/zig build simulator -Dsimulator-state-machine=accounting
      - run: zig/zig build simulator -Dsimulator-state-machine=testing

  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        debug: ["debug", "production"]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2

      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}
          flavor: |
            latest=${{ github.ref == 'refs/heads/main' && matrix.debug == 'production' }}
          # Each line here is a tag.
          tags: |
            ${{ inputs.version != '' && format('{0}{1}', inputs.version, matrix.debug == 'debug' && '-debug' || '') || '' }}
            ${{ github.ref == 'refs/heads/main' && matrix.debug == 'debug' && 'debug' || '' }}

      - name: 'Build Docker Container'
        uses: docker/build-push-action@v4
        with:
          build-args: |
            DEBUG=${{ matrix.debug == 'debug' && 'true' || 'false' }}

          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: release
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
          file: tools/docker/Dockerfile
          # So that we can copy in .git to the build step so we can
          # get the correct version.
          context: .

      # This is required because we can't load multiple platforms. Instead,
      # just load amd64 for verification below.
      - name: 'Load Docker Container'
        id: docker_load
        uses: docker/build-push-action@v4
        with:
          build-args: |
            DEBUG=${{ matrix.debug == 'debug' && 'true' || 'false' }}

          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: release
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          file: tools/docker/Dockerfile
          # So that we can copy in .git to the build step so we can
          # get the correct version.
          context: .

      # Validate the image
      - if: matrix.debug == 'production'
        run: ./.github/ci/confirm_image.sh ${{ steps.docker_load.outputs.imageid }} --want-production
      - if: matrix.debug == 'debug'
        run: ./.github/ci/confirm_image.sh ${{ steps.docker_load.outputs.imageid }} --want-debug

      # Login and publish, if we're in a release
      - if: inputs.version != ''
        name: 'Login to Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - if: inputs.version != ''
        name: 'Push Docker Container'
        uses: docker/build-push-action@v4
        with:
          build-args: |
            DEBUG=${{ matrix.debug == 'debug' && 'true' || 'false' }}

          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: release
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
          file: tools/docker/Dockerfile
          # So that we can copy in .git to the build step so we can
          # get the correct version.
          context: .
