name: "Release (artifacts)"

on:
  # This only works for if you manually publish a release
  release:
    types: [published]

  workflow_call:
    inputs:
      dry-run:
        required: false
        type: string
      version:
        required: false
        type: string

jobs:
  version:
    outputs:
      version: ${{ steps.calculate_version.outputs.version }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0
    - id: calculate_version
      run: |
        version="${{ inputs.version }}"
        if [[ "$version" == ""  ]]; then
          # Must have been called from a manual release
          version="$(git tag --points-at ${{ github.sha }})"
        fi
        echo "version=$version" >> "$GITHUB_OUTPUT"
  
  build_and_upload_binaries:
    needs: version
    strategy:
      matrix:
        debug: ["", "--debug"]
        target: [aarch64-linux, x86_64-linux, aarch64-macos, x86_64-macos, x86_64-windows]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        # By default, this will do a shallow clone and won't have tags - which we need.
        # https://github.com/actions/checkout/issues/701
        submodules: recursive
        fetch-depth: 0

    - name: Build tigerbeetle
      run: ./scripts/install.sh ${{ matrix.debug }}
      env:
        TARGET: ${{ matrix.target }}
        CPU: ${{ matrix.target == 'aarch64-linux' && 'baseline+aes+neon' || matrix.target == 'aarch64-macos' && 'baseline+aes+neon' || 'x86_64_v3+aes' }}

    # Use github.sha, not HEAD, so we can't have any race conditions where a new commit gets
    # pushed before this pipeline runs. When invoked by workflow_call, this will be set to
    # the value that triggered the parent workflow. Even though technically that's a scheduled
    # call, GH set it to the last commit on the default branch.
    - name: Upload on release
      if: ${{ inputs.dry-run != 'true' }}
      run: |
        export GIT_TAG="${{ needs.version.outputs.version }}" && \
        export RELEASE_ID=`curl -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' "https://api.github.com/repos/tigerbeetledb/tigerbeetle/releases/tags/${GIT_TAG}" | jq '.id'` && \
        export BINARY="$([ ${{ matrix.target }} = x86_64-windows ] && echo tigerbeetle.exe || echo tigerbeetle)" && \
        zip -9 tigerbeetle-${{ matrix.target }}-${GIT_TAG}${{ matrix.debug }}.zip $BINARY && \
        curl --fail \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/zip" \
          --data-binary @./tigerbeetle-${{ matrix.target }}-${GIT_TAG}${{ matrix.debug }}.zip \
          "https://uploads.github.com/repos/tigerbeetledb/tigerbeetle/releases/$RELEASE_ID/assets?name=tigerbeetle-${{ matrix.target }}-${GIT_TAG}${{ matrix.debug }}.zip"

  # Publish all clients and Docker image.

  client-dotnet:
    needs: version
    uses: ./.github/workflows/clients-dotnet.yml
    secrets:
      NUGET_KEY: ${{ secrets.NUGET_KEY }}
    with:
      version: ${{needs.version.outputs.version}}

  client-go:
    needs: version
    uses: ./.github/workflows/clients-go.yml
    secrets:
      TIGERBEETLE_GO_DEPLOY_KEY: ${{ secrets.TIGERBEETLE_GO_DEPLOY_KEY }}
    with:
      version: ${{needs.version.outputs.version}}

  client-java:
    needs: version
    uses: ./.github/workflows/clients-java.yml
    secrets:
      MAVEN_GPG_SECRET_KEY: ${{ secrets.MAVEN_GPG_SECRET_KEY }}
      MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
      MAVEN_GPG_SECRET_KEY_PASSWORD: ${{ secrets.MAVEN_GPG_SECRET_KEY_PASSWORD }}
    with:
      version: ${{needs.version.outputs.version}}

  client-node:
    needs: version
    uses: ./.github/workflows/clients-node.yml
    secrets:
      TIGERBEETLE_NODE_PUBLISH_KEY: ${{ secrets.TIGERBEETLE_NODE_PUBLISH_KEY }}
    with:
      version: ${{needs.version.outputs.version}}

  # For the Docker image
  linux:
    needs: version
    uses: ./.github/workflows/linux.yml
    with:
      version: ${{needs.version.outputs.version}}
