name: Build and publish artifacts

on:
  release:
    types: [published]

jobs:
  build_and_upload_binaries:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

        debug: ["", "--debug"]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Build tigerbeetle
      run: ./scripts/install.sh ${{ matrix.debug }}

    - name: Store current tag
      run: echo "GIT_TAG=`git tag --points-at HEAD`" >> $GITHUB_ENV

    # Note: this only creates builds on the platform being built. So
    # this does not build for M1 Macs. Maybe in the future we could
    # use Zig's cross-platform builds instead of relying on the
    # current platform and different Github Actions runners.
    - name: Create zip of release build
      run: zip -9 tigerbeetle-$RUNNER_OS-x64-$GIT_TAG.zip tigerbeetle

    - name: Get Github ID for tag
      run: |
        echo "RELEASE_ID=`curl -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/tigerbeetledb/tigerbeetle/releases/tags/$GIT_TAG | jq '.id'`" >> $GITHUB_ENV
    - name: Upload on release
      run: |
        curl --fail \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/zip" \
          --data-binary @./tigerbeetle-$RUNNER_OS-x64-$GIT_TAG.zip \
          "https://uploads.github.com/repos/tigerbeetledb/tigerbeetle/releases/$RELEASE_ID/assets?name=tigerbeetle-$RUNNER_OS-x64-$GIT_TAG.zip"
