name: "Release (latest)"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  version:
    outputs:
      version: ${{ steps.calculate_version.outputs.version }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: calculate_version
      run: |
        echo "version=$(./scripts/next_version.sh)" >> "$GITHUB_OUTPUT"
  
  scheduled_release:
    runs-on: ubuntu-latest
    needs: [version]
    steps:
      - uses: actions/checkout@v3

      # Explicitly pass in the sha, even though it's very likely to be HEAD.
      - run: |
          hub release create \
            --prerelease \
            --message "$(./scripts/generate_release_message.sh ${{ needs.version.outputs.version }})" \
            -t ${{ github.sha }} \
            "${{ needs.version.outputs.version }}"

        # Propagate token into environment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Even though the release job has an on: release trigger, actions taken by GITHUB_TOKEN
  # don't trigger this, so we call it here
  # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
  release:
    needs: [scheduled_release, version]
    uses: ./.github/workflows/release_artifacts.yml
    with:
      version: ${{needs.version.outputs.version}}
    secrets:
      TIGERBEETLE_NODE_PUBLISH_KEY: ${{secrets.TIGERBEETLE_NODE_PUBLISH_KEY}}
      NUGET_KEY: ${{secrets.NUGET_KEY}}
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      MAVEN_GPG_SECRET_KEY: ${{ secrets.MAVEN_GPG_SECRET_KEY }}
      MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
      MAVEN_GPG_SECRET_KEY_PASSWORD: ${{ secrets.MAVEN_GPG_SECRET_KEY_PASSWORD }}
      TIGERBEETLE_GO_DEPLOY_KEY: ${{ secrets.TIGERBEETLE_GO_DEPLOY_KEY }}
