on:
  schedule:
    # Every Monday at 14:00
    - cron: "0 14 * * 1"
jobs:
  scheduled_release:
    runs-on: ubuntu-latest
    steps:
      - run: hub release create -m "Weekly automated build. Do not use in production." "$(date +%Y%m%d%H%M%S)-weekly"
